---
collections:
  - name: community.routeros
    version: 2.7.0
  - name: community.general
    version: 6.3.0
  - name: ansible.netcommon
    version: 4.1.0
  - name: ansible.utils
    version: 2.9.0